### ISSUE TITLE
hexo主题迁移and折腾记 | weearc的个人博客

### ISSUE THREAD

**Issue by weearc** [weearc/weearc.github.io#2]
https://blog.weearc.top/posts/6009.html 

 相离相惜莫相忘，且行且歌且珍惜

**Comment by weearc** [comment]
完了…错字受…

**Comment by weearc** [comment]
这是一条来自Windows10 1709 chrome 67 的消息。很快就会变成Windows10 1803 chrome 73 了

**Comment by EEEIXXX** [comment]
楼主，把进度条那个添加进head.pug后，hexo g报错是怎么回事？
```
ERROR Process failed: layout/base-without-sidebar.pug
Error: /home/eeeixxx/hexo/themes/maupassant/layout/_partial/head.pug:38:5
    36|           s.parentNode.insertBefore(hm, s);                                                                  
    37|           }                                                                                                  
  > 38|  //- 插入进度条                                                                                              
------------^                                                                                                        
    39|  script(src='//cdn.bootcss.com/pace/1.0.2/pace.min.js')                                                      
    40|  link(href='//cdn.bootcss.com/pace/1.0.2/themes/pink/pace-theme-flash.css', rel='stylesheet')                
    41|  style.                                                                                                      

Inconsistent indentation. Expecting either 0 or 4 spaces/tabs.                                                       
    at makeError (/home/eeeixxx/hexo/node_modules/pug-error/index.js:32:13)                                          
    at Lexer.error (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:52:15)                                        
    at Lexer.indent (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1159:18)                                     
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.advance (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1305:15)                                    
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.getTokens (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1322:12)                                  
    at Object.lex (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:12:42)                                         
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:39:24)                   
    at /home/eeeixxx/hexo/node_modules/pug-loader/index.js:30:27                                                     
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:13:26)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:33:21)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at load (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:12:10)                                              
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:41:10)                   
    at compileBody (/home/eeeixxx/hexo/node_modules/pug/lib/index.js:55:18)                                          
    at Object.exports.compile (/home/eeeixxx/hexo/node_modules/pug/lib/index.js:152:16)                              
ERROR Process failed: layout/archive.pug
Error: /home/eeeixxx/hexo/themes/maupassant/layout/_partial/head.pug:38:5
    36|           s.parentNode.insertBefore(hm, s);                                                                  
    37|           }                                                                                                  
  > 38|  //- 插入进度条                                                                                              
------------^                                                                                                        
    39|  script(src='//cdn.bootcss.com/pace/1.0.2/pace.min.js')                                                      
    40|  link(href='//cdn.bootcss.com/pace/1.0.2/themes/pink/pace-theme-flash.css', rel='stylesheet')                
    41|  style.                                                                                                      

Inconsistent indentation. Expecting either 0 or 4 spaces/tabs.                                                       
    at makeError (/home/eeeixxx/hexo/node_modules/pug-error/index.js:32:13)                                          
    at Lexer.error (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:52:15)                                        
    at Lexer.indent (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1159:18)                                     
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.advance (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1305:15)                                    
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.getTokens (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1322:12)                                  
    at Object.lex (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:12:42)                                         
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:39:24)                   
    at /home/eeeixxx/hexo/node_modules/pug-loader/index.js:30:27                                                     
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:13:26)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:33:21)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at load (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:12:10)                                              
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:41:10)                   
    at /home/eeeixxx/hexo/node_modules/pug-loader/index.js:30:27                                                     
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:13:26)                                             
ERROR Process failed: layout/base.pug
Error: /home/eeeixxx/hexo/themes/maupassant/layout/_partial/head.pug:38:5
    36|           s.parentNode.insertBefore(hm, s);                                                                  
    37|           }                                                                                                  
  > 38|  //- 插入进度条                                                                                              
------------^                                                                                                        
    39|  script(src='//cdn.bootcss.com/pace/1.0.2/pace.min.js')                                                      
    40|  link(href='//cdn.bootcss.com/pace/1.0.2/themes/pink/pace-theme-flash.css', rel='stylesheet')                
    41|  style.                                                                                                      

Inconsistent indentation. Expecting either 0 or 4 spaces/tabs.                                                       
    at makeError (/home/eeeixxx/hexo/node_modules/pug-error/index.js:32:13)                                          
    at Lexer.error (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:52:15)                                        
    at Lexer.indent (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1159:18)                                     
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.advance (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1305:15)                                    
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.getTokens (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1322:12)                                  
    at Object.lex (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:12:42)                                         
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:39:24)                   
    at /home/eeeixxx/hexo/node_modules/pug-loader/index.js:30:27                                                     
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:13:26)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:33:21)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at load (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:12:10)                                              
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:41:10)                   
    at compileBody (/home/eeeixxx/hexo/node_modules/pug/lib/index.js:55:18)                                          
    at Object.exports.compile (/home/eeeixxx/hexo/node_modules/pug/lib/index.js:152:16)                              
ERROR Process failed: layout/index.pug
Error: /home/eeeixxx/hexo/themes/maupassant/layout/_partial/head.pug:38:5
    36|           s.parentNode.insertBefore(hm, s);                                                                  
    37|           }                                                                                                  
  > 38|  //- 插入进度条                                                                                              
------------^                                                                                                        
    39|  script(src='//cdn.bootcss.com/pace/1.0.2/pace.min.js')                                                      
    40|  link(href='//cdn.bootcss.com/pace/1.0.2/themes/pink/pace-theme-flash.css', rel='stylesheet')                
    41|  style.                                                                                                      

Inconsistent indentation. Expecting either 0 or 4 spaces/tabs.                                                       
    at makeError (/home/eeeixxx/hexo/node_modules/pug-error/index.js:32:13)                                          
    at Lexer.error (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:52:15)                                        
    at Lexer.indent (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1159:18)                                     
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.advance (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1305:15)                                    
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.getTokens (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1322:12)                                  
    at Object.lex (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:12:42)                                         
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:39:24)                   
    at /home/eeeixxx/hexo/node_modules/pug-loader/index.js:30:27                                                     
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:13:26)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:33:21)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at load (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:12:10)                                              
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:41:10)                   
    at /home/eeeixxx/hexo/node_modules/pug-loader/index.js:30:27                                                     
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:13:26)                                             
ERROR Process failed: layout/post.pug
Error: /home/eeeixxx/hexo/themes/maupassant/layout/_partial/head.pug:38:5
    36|           s.parentNode.insertBefore(hm, s);                                                                  
    37|           }                                                                                                  
  > 38|  //- 插入进度条                                                                                              
------------^                                                                                                        
    39|  script(src='//cdn.bootcss.com/pace/1.0.2/pace.min.js')                                                      
    40|  link(href='//cdn.bootcss.com/pace/1.0.2/themes/pink/pace-theme-flash.css', rel='stylesheet')                
    41|  style.                                                                                                      

Inconsistent indentation. Expecting either 0 or 4 spaces/tabs.                                                       
    at makeError (/home/eeeixxx/hexo/node_modules/pug-error/index.js:32:13)                                          
    at Lexer.error (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:52:15)                                        
    at Lexer.indent (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1159:18)                                     
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.advance (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1305:15)                                    
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.getTokens (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1322:12)                                  
    at Object.lex (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:12:42)                                         
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:39:24)                   
    at /home/eeeixxx/hexo/node_modules/pug-loader/index.js:30:27                                                     
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:13:26)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:33:21)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at load (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:12:10)                                              
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:41:10)                   
    at /home/eeeixxx/hexo/node_modules/pug-loader/index.js:30:27                                                     
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:13:26)                                             
ERROR Process failed: layout/page.pug
Error: /home/eeeixxx/hexo/themes/maupassant/layout/_partial/head.pug:38:5
    36|           s.parentNode.insertBefore(hm, s);                                                                  
    37|           }                                                                                                  
  > 38|  //- 插入进度条                                                                                              
------------^                                                                                                        
    39|  script(src='//cdn.bootcss.com/pace/1.0.2/pace.min.js')                                                      
    40|  link(href='//cdn.bootcss.com/pace/1.0.2/themes/pink/pace-theme-flash.css', rel='stylesheet')                
    41|  style.                                                                                                      

Inconsistent indentation. Expecting either 0 or 4 spaces/tabs.                                                       
    at makeError (/home/eeeixxx/hexo/node_modules/pug-error/index.js:32:13)                                          
    at Lexer.error (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:52:15)                                        
    at Lexer.indent (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1159:18)                                     
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.advance (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1305:15)                                    
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.getTokens (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1322:12)                                  
    at Object.lex (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:12:42)                                         
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:39:24)                   
    at /home/eeeixxx/hexo/node_modules/pug-loader/index.js:30:27                                                     
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:13:26)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:33:21)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at load (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:12:10)                                              
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:41:10)                   
    at /home/eeeixxx/hexo/node_modules/pug-loader/index.js:30:27                                                     
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:13:26)                                             
ERROR Process failed: layout/single-column.pug
Error: /home/eeeixxx/hexo/themes/maupassant/layout/_partial/head.pug:38:5
    36|           s.parentNode.insertBefore(hm, s);                                                                  
    37|           }                                                                                                  
  > 38|  //- 插入进度条                                                                                              
------------^                                                                                                        
    39|  script(src='//cdn.bootcss.com/pace/1.0.2/pace.min.js')                                                      
    40|  link(href='//cdn.bootcss.com/pace/1.0.2/themes/pink/pace-theme-flash.css', rel='stylesheet')                
    41|  style.                                                                                                      

Inconsistent indentation. Expecting either 0 or 4 spaces/tabs.                                                       
    at makeError (/home/eeeixxx/hexo/node_modules/pug-error/index.js:32:13)                                          
    at Lexer.error (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:52:15)                                        
    at Lexer.indent (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1159:18)                                     
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.advance (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1305:15)                                    
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.getTokens (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1322:12)                                  
    at Object.lex (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:12:42)                                         
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:39:24)                   
    at /home/eeeixxx/hexo/node_modules/pug-loader/index.js:30:27                                                     
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:13:26)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:33:21)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at load (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:12:10)                                              
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:41:10)                   
    at /home/eeeixxx/hexo/node_modules/pug-loader/index.js:30:27                                                     
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:13:26)                                             
ERROR Process failed: layout/timeline.pug
Error: /home/eeeixxx/hexo/themes/maupassant/layout/_partial/head.pug:38:5
    36|           s.parentNode.insertBefore(hm, s);                                                                  
    37|           }                                                                                                  
  > 38|  //- 插入进度条                                                                                              
------------^                                                                                                        
    39|  script(src='//cdn.bootcss.com/pace/1.0.2/pace.min.js')                                                      
    40|  link(href='//cdn.bootcss.com/pace/1.0.2/themes/pink/pace-theme-flash.css', rel='stylesheet')                
    41|  style.                                                                                                      

Inconsistent indentation. Expecting either 0 or 4 spaces/tabs.                                                       
    at makeError (/home/eeeixxx/hexo/node_modules/pug-error/index.js:32:13)                                          
    at Lexer.error (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:52:15)                                        
    at Lexer.indent (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1159:18)                                     
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.advance (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1305:15)                                    
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.getTokens (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1322:12)                                  
    at Object.lex (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:12:42)                                         
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:39:24)                   
    at /home/eeeixxx/hexo/node_modules/pug-loader/index.js:30:27                                                     
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:13:26)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:33:21)                                             
    at /home/eeeixxx/hexo/node_modules/pug-walk/index.js:21:16                                                       
    at Array.map (<anonymous>)                                                                                       
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:20:29)                                             
    at load (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:12:10)                                              
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:41:10)                   
    at /home/eeeixxx/hexo/node_modules/pug-loader/index.js:30:27                                                     
    at walkAST (/home/eeeixxx/hexo/node_modules/pug-walk/index.js:13:26)                                             
ERROR Process failed: layout/_partial/head.pug
Error: /home/eeeixxx/hexo/themes/maupassant/layout/_partial/head.pug:38:5
    36|           s.parentNode.insertBefore(hm, s);                                                                  
    37|           }                                                                                                  
  > 38|  //- 插入进度条                                                                                              
------------^                                                                                                        
    39|  script(src='//cdn.bootcss.com/pace/1.0.2/pace.min.js')                                                      
    40|  link(href='//cdn.bootcss.com/pace/1.0.2/themes/pink/pace-theme-flash.css', rel='stylesheet')                
    41|  style.                                                                                                      

Inconsistent indentation. Expecting either 0 or 4 spaces/tabs.                                                       
    at makeError (/home/eeeixxx/hexo/node_modules/pug-error/index.js:32:13)                                          
    at Lexer.error (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:52:15)                                        
    at Lexer.indent (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1159:18)                                     
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.advance (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1305:15)                                    
    at Lexer.callLexerFunction (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1266:23)                          
    at Lexer.getTokens (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:1322:12)                                  
    at Object.lex (/home/eeeixxx/hexo/node_modules/pug-lexer/index.js:12:42)                                         
    at Function.loadString [as string] (/home/eeeixxx/hexo/node_modules/pug-loader/index.js:39:24)                   
    at compileBody (/home/eeeixxx/hexo/node_modules/pug/lib/index.js:55:18)                                          
    at Object.exports.compile (/home/eeeixxx/hexo/node_modules/pug/lib/index.js:152:16)                              
    at Function.pugCompile [as compile] (/home/eeeixxx/hexo/node_modules/hexo-renderer-pug/lib/renderer.js:6:16)     
    at Theme._View.View.View._precompile (/home/eeeixxx/hexo/node_modules/hexo/lib/theme/view.js:118:31)             
    at Theme._View.View.View (/home/eeeixxx/hexo/node_modules/hexo/lib/theme/view.js:14:8)                           
    at new Theme._View.View (/home/eeeixxx/hexo/node_modules/hexo/lib/theme/index.js:37:10)                          
    at Theme.setView (/home/eeeixxx/hexo/node_modules/hexo/lib/theme/index.js:71:20)                                 
    at file.read.then.result (/home/eeeixxx/hexo/node_modules/hexo/lib/theme/processors/view.js:14:14)               
    at tryCatcher (/home/eeeixxx/hexo/node_modules/bluebird/js/release/util.js:16:23)                                
    at Promise._settlePromiseFromHandler (/home/eeeixxx/hexo/node_modules/bluebird/js/release/promise.js:512:31)     
    at Promise._settlePromise (/home/eeeixxx/hexo/node_modules/bluebird/js/release/promise.js:569:18)                
    at Promise._settlePromise0 (/home/eeeixxx/hexo/node_modules/bluebird/js/release/promise.js:614:10)               
    at Promise._settlePromises (/home/eeeixxx/hexo/node_modules/bluebird/js/release/promise.js:694:18)               
INFO  Files loaded in 570 ms
```

**Comment by weearc** [comment]
@EEEIXXX
请使用markdown的代码格式把代码部分括起来…另外你注意看报错，全部指向了我写的注释部分，请把注释去掉看看。

**Comment by weearc** [comment]
@EEEIXXX  修改了一下你的comment...大量重复的报错会导致咱的页面加载比较卡顿了
